### ISSUE TITLE
Data Structure declared using LikeDS keyword populating End-DS

### ISSUE THREAD

**Issue by yusy4code** [worksofbarry/rpgfreeweb#8]
<pre>D StudInfo        DS                  LikeDS(UserInfo) </pre>

For the above line of code, we get below result which has End-DS; 

```
Dcl-DS StudInfo  LikeDS(UserInfo);
End-DS;
```

Compilation error:
     7         Dcl-DS StudInfo  LikeDS(UserInfo);  
     8         End-DS;                             
======>        aaaaaa                              
*RNF3551 20 a      000800  END-XX is not expected.

**Comment by BrianGarland** [comment]
I think this issue has been resolved by a previous pull request.  I can no longer reproduce it.
