### ISSUE TITLE
long name in data structures converts to invalid "end-ds"

### ISSUE THREAD

**Issue by Lundis** [worksofbarry/rpgfreeweb#9]
dref_cardRuleInfo...
     d                 ds                  qualified template
     d productId                     10i 0
     d accountsAreOptional...
     d                                 n 

Becomes:

        Dcl-DS ref_cardRuleInfo  qualified template;
          productId      Int(10);
        End-DS;
        accountsAreOptional Ind;
        End-DS;

Instead of:

        Dcl-DS ref_cardRuleInfo  qualified template;
          productId      Int(10);
          accountsAreOptional Ind;
        End-DS;

**Comment by BrianGarland** [comment]
Pull request #18 should fix this.

**Comment by BrianGarland** [comment]
I think this issue was resolved by a previous pull request.  I can no longer reproduce it.
